---
- hosts: django
  become:
    true
  become_method:
    su
  become_user:
    root
  remote_user:
    root
  roles:
    - servergeneral
    - nginx
    - mysql
    - django
    - gunicorn
    - download
